version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
  - dependency-name: lodash
    versions:
    - 4.17.20
